FROM grnydawn/act3_base:v1
MAINTAINER Youngsung Kim<grnydawn@gmail.com>
RUN apt-get install -y git
RUN git config --global user.name "Youngsung Kim"
RUN git config --global user.email grnydawn@gmail.com
WORKDIR /root
EXPOSE 8080 9090
COPY ./entrypoint.sh /root
RUN mkdir /root/shared
VOLUME /root/shared
ENTRYPOINT ["/bin/bash", "./entrypoint.sh"]
